markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Cubian
url: http://cubian.org
subscribe: http://cubian.org/feed.xml
exclude: [ README.md, newpost.rb ]
domain: cubian.org
disqusShortname: cubian
highlighter: pygments
googleAnalyticsID: UA-42738908-1

